version: "3.2"

volumes:
  redis:
    external: true

services:
  redis:
    container_name: redis_custom_cian
    image: redis:alpine
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
        - 6379:6379
    volumes:
        - $PWD/redis-data:/var/lib/redis
        - $PWD/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
        - REDIS_REPLICATION_MODE=master
        - TZ=Europe/Moscow
