version: "3.2"

volumes:
  redis_custom_cian:
    external: true
  postgres_custom_cian:
    external: true


services:
  redis:
    container_name: redis_custom_cian
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
        - 6379:6379
    volumes:
        - ${PWD}/redis-data:/var/lib/redis
        - ${PWD}/conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
        - REDIS_REPLICATION_MODE=${REDIS_REPLICATION_MODE}
        - TZ=${TZ}

  database:
    container_name: postgres_custom_cian
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_custom_cian:/var/lib/postgresql/data
    env_file:
      - ./.env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
