# Generated by Django 3.1.5 on 2021-01-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210125_0928'),
        ('main', '0002_auto_20210125_1325'),
    ]

    operations = [
    ]
