# Generated by Django 3.1.5 on 2021-01-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20210126_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='Ссылка'),
        ),
    ]
