# Generated by Django 3.1.5 on 2021-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_saller_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='saller',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
