# Generated by Django 3.1.5 on 2021-01-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_saller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
