# Generated by Django 3.1.5 on 2021-02-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
