# Generated by Django 3.1.5 on 2021-02-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210208_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
