# Generated by Django 3.1.5 on 2021-02-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_realty_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='in_archive',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
