# Generated by Django 3.1.5 on 2021-03-01 15:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_realty_in_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realty',
            name='tags',
        ),
        migrations.AddField(
            model_name='realty',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
