# Generated by Django 3.1.5 on 2021-03-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_tag_realty_list'),
    ]

    sql = """
        CREATE OR REPLACE VIEW userrealty AS
        SELECT a.id as user_id, a.first_name as first_name, a.last_name as last_name,
        r.name AS realty_title, r.description AS realty_description,
        r.tags AS tags
        FROM main_realty as r
        INNER JOIN main_saller AS s on s.id = r.saller_id
        INNER JOIN auth_user AS a on a.id = s.created_by_id
        """

    operations = [
        migrations.RunSQL(sql)
    ]
